#!/bin/bash

# Paste in Babun
echo "set mouse-=a" >> ~/.vimrc 
#INSTALL PIP
wget https://bootstrap.pypa.io/ez_setup.py -O - | python
easy_install pip
pip install mercurial-keyring

#INSTALL ANSIBLE
curl -s https://raw.githubusercontent.com/tiangolo/ansible-babun-bootstrap/master/install.sh | source /dev/stdin

#Dependency of ansible  
                        # ecdsa
                        # pycrypto
                        # paramiko
pip install pyyaml	# YAML
easy_install Jinja2	# jinja2
#
